name: Linter and unit tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.7
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun lint
      - name: build
        run: bun build
      - name: unit tests
        run: bun test:unit
